- hosts: alt
  sudo: True
  user: bozicsr      
  tasks: 
   - name: Instalacija paketa
     yum: pkg={{item}} state=installed   
     with_items:
       - screen
       - iotop
       - iptraf
       - acpid
       - man
       - bind-utils
       - vim-enhanced
       - nc
       - zip
       - unzip
       - wget
       - links
       - lsof
       - bash-completion
       - dos2unix
       - links
       - hdparm
       - smartmontools
       - kexec-tools
       - mc
       - mcelog
       - htop
       - net-tools
       - system-storage-manager
       - traceroute
       - ntp
       - net-snmp
       - bind-utils
       - iptraf

