---
- hosts: all
  user: bozicsr
  tasks:

  - name: put ssh-key in
    authorized_key: user=bozicsr key="{{lookup('file', '~/.ssh/id_rsa.pub') }}" manage_dir=yes

  - name: install packages
    yum: pkg={{ item }} state=installed
    when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6
    with_items:
       - screen
       - iotop 
       - iptraf 
       - acpid 
       - man 
       - bind-utils 
       - vim-enhanced 
       - nc 
       - zip 
       - unzip 
       - wget 
       - links 
       - screen 
       - lsof 
       - bash-completion 
       - dos2unix 
       - links 
       - hdparm 
       - smartmontools 
       - kexec-tools 
       - mc 
       - mcelog 

  - name: activate autoupdate
    service: enabled=yes state=started name=yum-cron

